In [1]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
df = pd.read_csv("Employee Attrition Data (1).csv")

In [5]:
df

       Age  Department JobSatisfaction  YearsAtCompany OverTime Attrition
0       59       Sales             NaN               2       no       Yes
1       36     Finance               2              11        N         Y
2       29     Finance               3               7        Y       Yes
3       42  Operations               4               5      Yes        no
4       40          HR               1              10       No        No
5       44     Finance               2               2       No         N
6       32          HR             NaN               0        N       Yes
7       32         R&D               1               2      Yes         N
8       45     Finance               4               4      Yes       yes
9       57  Operations               1              14      Yes         N
10      45  Operations               2              13        N         Y
11      24     Finance               3               2      Yes        no
12      43          HR            four               0       no       yes
13      23  Operations               4               4      yes        No
14      45  Operations               2               9      Yes        No
15     NaN     Finance               1               6      yes         N
16      59         R&D               4              14      yes       Yes
17      23          HR               4              13        Y         Y
18      42         R&D               4               6        Y         N
19      54         R&D               1              10        N         N
20      33     Finance               1               8      yes        no
21      43          HR               1              14      Yes       yes
22      46       Sales               3              14       No         Y
23      48  Operations               1               9       No        No
24      49         R&D               1               9      yes       Yes
25      37          HR               1              11       No       yes
26      36     Finance               3              12      Yes         N
27      24  Operations               1               2      Yes         Y
28      58       Sales               4              14        Y       yes
29      28       Sales               1               6        N       yes
30      42       Sales               4               0       No        no
31      30       Sales               4               3      yes        no
32      39         R&D               4              12      yes        No
33  thirty       Sales               3               3      Yes       yes
34      46         R&D               3              13        N         Y
35      35     Finance               3               4        N       yes
36      30     Finance               1               6      Yes        no
37      47          HR               5               6        Y        no
38      23         R&D               3              12        Y         Y
39      41       Sales               2              14       no       yes
40      49         R&D               1              10        N         N
41      28         R&D               3              12      Yes        no
42      29       Sales               1               3        Y         Y
43      56     Finance               2              12       no        no
44      35  Operations               3               6        Y       yes
45      38  Operations               2              10       no        No
46      57  Operations               1               2       No        no
47      25          HR               4               5        Y       Yes
48      23         R&D               3              11      yes       yes
49      27  Operations               1               1        N       yes
50      25       Sales               4               9        Y       yes
51      50         R&D               4              12       No         N
52      39       Sales               2              13       No         Y
53      47       Sales               1               8        Y         N
54      55     Finance               4               4       no        no
55      31         R&D               3               5      yes       Yes
56      57  Operations               3              11        Y        no
57      35         R&D               2              11        N        No
58       0         R&D               4              11      Yes         Y
59      36       Sales               1              11        Y         Y

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              59 non-null     object
 1   Department       60 non-null     object
 2   JobSatisfaction  58 non-null     object
 3   YearsAtCompany   60 non-null     int64
 4   OverTime         60 non-null     object
 5   Attrition        60 non-null     object
dtypes: int64(1), object(5)
memory usage: 2.9+ KB

In [7]:
df.shape

(60, 6)

In [8]:
df.isnull().sum()

Age                1
Department         0
JobSatisfaction    2
YearsAtCompany     0
OverTime           0
Attrition          0
dtype: int64

In [9]:
kio = df.dropna(inplace= True )

In [10]:
kio

In [11]:
df.isnull().sum()

Age                0
Department         0
JobSatisfaction    0
YearsAtCompany     0
OverTime           0
Attrition          0
dtype: int64

In [12]:
df

       Age  Department JobSatisfaction  YearsAtCompany OverTime Attrition
1       36     Finance               2              11        N         Y
2       29     Finance               3               7        Y       Yes
3       42  Operations               4               5      Yes        no
4       40          HR               1              10       No        No
5       44     Finance               2               2       No         N
7       32         R&D               1               2      Yes         N
8       45     Finance               4               4      Yes       yes
9       57  Operations               1              14      Yes         N
10      45  Operations               2              13        N         Y
11      24     Finance               3               2      Yes        no
12      43          HR            four               0       no       yes
13      23  Operations               4               4      yes        No
14      45  Operations               2               9      Yes        No
16      59         R&D               4              14      yes       Yes
17      23          HR               4              13        Y         Y
18      42         R&D               4               6        Y         N
19      54         R&D               1              10        N         N
20      33     Finance               1               8      yes        no
21      43          HR               1              14      Yes       yes
22      46       Sales               3              14       No         Y
23      48  Operations               1               9       No        No
24      49         R&D               1               9      yes       Yes
25      37          HR               1              11       No       yes
26      36     Finance               3              12      Yes         N
27      24  Operations               1               2      Yes         Y
28      58       Sales               4              14        Y       yes
29      28       Sales               1               6        N       yes
30      42       Sales               4               0       No        no
31      30       Sales               4               3      yes        no
32      39         R&D               4              12      yes        No
33  thirty       Sales               3               3      Yes       yes
34      46         R&D               3              13        N         Y
35      35     Finance               3               4        N       yes
36      30     Finance               1               6      Yes        no
37      47          HR               5               6        Y        no
38      23         R&D               3              12        Y         Y
39      41       Sales               2              14       no       yes
40      49         R&D               1              10        N         N
41      28         R&D               3              12      Yes        no
42      29       Sales               1               3        Y         Y
43      56     Finance               2              12       no        no
44      35  Operations               3               6        Y       yes
45      38  Operations               2              10       no        No
46      57  Operations               1               2       No        no
47      25          HR               4               5        Y       Yes
48      23         R&D               3              11      yes       yes
49      27  Operations               1               1        N       yes
50      25       Sales               4               9        Y       yes
51      50         R&D               4              12       No         N
52      39       Sales               2              13       No         Y
53      47       Sales               1               8        Y         N
54      55     Finance               4               4       no        no
55      31         R&D               3               5      yes       Yes
56      57  Operations               3              11        Y        no
57      35         R&D               2              11        N        No
58       0         R&D               4              11      Yes         Y
59      36       Sales               1              11        Y         Y

In [13]:
df=df[df['Age'].str.isnumeric()]

In [14]:
df

   Age  Department JobSatisfaction  YearsAtCompany OverTime Attrition
1   36     Finance               2              11        N         Y
2   29     Finance               3               7        Y       Yes
3   42  Operations               4               5      Yes        no
4   40          HR               1              10       No        No
5   44     Finance               2               2       No         N
7   32         R&D               1               2      Yes         N
8   45     Finance               4               4      Yes       yes
9   57  Operations               1              14      Yes         N
10  45  Operations               2              13        N         Y
11  24     Finance               3               2      Yes        no
12  43          HR            four               0       no       yes
13  23  Operations               4               4      yes        No
14  45  Operations               2               9      Yes        No
16  59         R&D               4              14      yes       Yes
17  23          HR               4              13        Y         Y
18  42         R&D               4               6        Y         N
19  54         R&D               1              10        N         N
20  33     Finance               1               8      yes        no
21  43          HR               1              14      Yes       yes
22  46       Sales               3              14       No         Y
23  48  Operations               1               9       No        No
24  49         R&D               1               9      yes       Yes
25  37          HR               1              11       No       yes
26  36     Finance               3              12      Yes         N
27  24  Operations               1               2      Yes         Y
28  58       Sales               4              14        Y       yes
29  28       Sales               1               6        N       yes
30  42       Sales               4               0       No        no
31  30       Sales               4               3      yes        no
32  39         R&D               4              12      yes        No
34  46         R&D               3              13        N         Y
35  35     Finance               3               4        N       yes
36  30     Finance               1               6      Yes        no
37  47          HR               5               6        Y        no
38  23         R&D               3              12        Y         Y
39  41       Sales               2              14       no       yes
40  49         R&D               1              10        N         N
41  28         R&D               3              12      Yes        no
42  29       Sales               1               3        Y         Y
43  56     Finance               2              12       no        no
44  35  Operations               3               6        Y       yes
45  38  Operations               2              10       no        No
46  57  Operations               1               2       No        no
47  25          HR               4               5        Y       Yes
48  23         R&D               3              11      yes       yes
49  27  Operations               1               1        N       yes
50  25       Sales               4               9        Y       yes
51  50         R&D               4              12       No         N
52  39       Sales               2              13       No         Y
53  47       Sales               1               8        Y         N
54  55     Finance               4               4       no        no
55  31         R&D               3               5      yes       Yes
56  57  Operations               3              11        Y        no
57  35         R&D               2              11        N        No
58   0         R&D               4              11      Yes         Y
59  36       Sales               1              11        Y         Y

In [15]:
df=df[df['JobSatisfaction'].str.isnumeric()]

In [16]:
df

   Age  Department JobSatisfaction  YearsAtCompany OverTime Attrition
1   36     Finance               2              11        N         Y
2   29     Finance               3               7        Y       Yes
3   42  Operations               4               5      Yes        no
4   40          HR               1              10       No        No
5   44     Finance               2               2       No         N
7   32         R&D               1               2      Yes         N
8   45     Finance               4               4      Yes       yes
9   57  Operations               1              14      Yes         N
10  45  Operations               2              13        N         Y
11  24     Finance               3               2      Yes        no
13  23  Operations               4               4      yes        No
14  45  Operations               2               9      Yes        No
16  59         R&D               4              14      yes       Yes
17  23          HR               4              13        Y         Y
18  42         R&D               4               6        Y         N
19  54         R&D               1              10        N         N
20  33     Finance               1               8      yes        no
21  43          HR               1              14      Yes       yes
22  46       Sales               3              14       No         Y
23  48  Operations               1               9       No        No
24  49         R&D               1               9      yes       Yes
25  37          HR               1              11       No       yes
26  36     Finance               3              12      Yes         N
27  24  Operations               1               2      Yes         Y
28  58       Sales               4              14        Y       yes
29  28       Sales               1               6        N       yes
30  42       Sales               4               0       No        no
31  30       Sales               4               3      yes        no
32  39         R&D               4              12      yes        No
34  46         R&D               3              13        N         Y
35  35     Finance               3               4        N       yes
36  30     Finance               1               6      Yes        no
37  47          HR               5               6        Y        no
38  23         R&D               3              12        Y         Y
39  41       Sales               2              14       no       yes
40  49         R&D               1              10        N         N
41  28         R&D               3              12      Yes        no
42  29       Sales               1               3        Y         Y
43  56     Finance               2              12       no        no
44  35  Operations               3               6        Y       yes
45  38  Operations               2              10       no        No
46  57  Operations               1               2       No        no
47  25          HR               4               5        Y       Yes
48  23         R&D               3              11      yes       yes
49  27  Operations               1               1        N       yes
50  25       Sales               4               9        Y       yes
51  50         R&D               4              12       No         N
52  39       Sales               2              13       No         Y
53  47       Sales               1               8        Y         N
54  55     Finance               4               4       no        no
55  31         R&D               3               5      yes       Yes
56  57  Operations               3              11        Y        no
57  35         R&D               2              11        N        No
58   0         R&D               4              11      Yes         Y
59  36       Sales               1              11        Y         Y

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 55 entries, 1 to 59
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              55 non-null     object
 1   Department       55 non-null     object
 2   JobSatisfaction  55 non-null     object
 3   YearsAtCompany   55 non-null     int64
 4   OverTime         55 non-null     object
 5   Attrition        55 non-null     object
dtypes: int64(1), object(5)
memory usage: 3.0+ KB

In [24]:
df["Department"].value_counts()

Department
R&D           15
Operations    12
Finance       11
Sales         11
HR             6
Name: count, dtype: int64

In [25]:
df["OverTime"].value_counts()

OverTime
Y      13
Yes    12
N       9
No      9
yes     8
no      4
Name: count, dtype: int64

In [26]:
df["OverTime"].replace({"Y":1,"N":0}, inplace = True)
df["OverTime"].replace({"yes":1,"no":0}, inplace = True)
df["OverTime"].replace({"Yes":1,"No":0}, inplace = True)

C:\Users\Anaam Ullah\AppData\Local\Temp\ipykernel_4864\3639355499.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["OverTime"].replace({"Y":1,"N":0}, inplace = True)
C:\Users\Anaam Ullah\AppData\Local\Temp\ipykernel_4864\3639355499.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["OverTime"].replace({"yes":1,"no":0}, inplace = True)
C:\Users\Anaam Ullah\AppData\Local\Temp\ipykernel_4864\3639355499.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["OverTime"].replace({"Yes":1,"No":0}, inplace = True)
C:\Users\Anaam Ullah\AppData\Local\Temp\ipykernel_4864\3639355499.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["OverTime"].replace({"Yes":1,"No":0}, inplace = True)

In [27]:
df

   Age  Department JobSatisfaction  YearsAtCompany  OverTime Attrition
1   36     Finance               2              11         0         Y
2   29     Finance               3               7         1       Yes
3   42  Operations               4               5         1        no
4   40          HR               1              10         0        No
5   44     Finance               2               2         0         N
7   32         R&D               1               2         1         N
8   45     Finance               4               4         1       yes
9   57  Operations               1              14         1         N
10  45  Operations               2              13         0         Y
11  24     Finance               3               2         1        no
13  23  Operations               4               4         1        No
14  45  Operations               2               9         1        No
16  59         R&D               4              14         1       Yes
17  23          HR               4              13         1         Y
18  42         R&D               4               6         1         N
19  54         R&D               1              10         0         N
20  33     Finance               1               8         1        no
21  43          HR               1              14         1       yes
22  46       Sales               3              14         0         Y
23  48  Operations               1               9         0        No
24  49         R&D               1               9         1       Yes
25  37          HR               1              11         0       yes
26  36     Finance               3              12         1         N
27  24  Operations               1               2         1         Y
28  58       Sales               4              14         1       yes
29  28       Sales               1               6         0       yes
30  42       Sales               4               0         0        no
31  30       Sales               4               3         1        no
32  39         R&D               4              12         1        No
34  46         R&D               3              13         0         Y
35  35     Finance               3               4         0       yes
36  30     Finance               1               6         1        no
37  47          HR               5               6         1        no
38  23         R&D               3              12         1         Y
39  41       Sales               2              14         0       yes
40  49         R&D               1              10         0         N
41  28         R&D               3              12         1        no
42  29       Sales               1               3         1         Y
43  56     Finance               2              12         0        no
44  35  Operations               3               6         1       yes
45  38  Operations               2              10         0        No
46  57  Operations               1               2         0        no
47  25          HR               4               5         1       Yes
48  23         R&D               3              11         1       yes
49  27  Operations               1               1         0       yes
50  25       Sales               4               9         1       yes
51  50         R&D               4              12         0         N
52  39       Sales               2              13         0         Y
53  47       Sales               1               8         1         N
54  55     Finance               4               4         0        no
55  31         R&D               3               5         1       Yes
56  57  Operations               3              11         1        no
57  35         R&D               2              11         0        No
58   0         R&D               4              11         1         Y
59  36       Sales               1              11         1         Y

In [28]:
df["Attrition"].replace({"Y":1,"N":0}, inplace = True)
df["Attrition"].replace({"yes":1,"no":0}, inplace = True)
df["Attrition"].replace({"Yes":1,"No":0}, inplace = True)

C:\Users\Anaam Ullah\AppData\Local\Temp\ipykernel_4864\60782308.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Attrition"].replace({"Y":1,"N":0}, inplace = True)
C:\Users\Anaam Ullah\AppData\Local\Temp\ipykernel_4864\60782308.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Attrition"].replace({"Y":1,"N":0}, inplace = True)
C:\Users\Anaam Ullah\AppData\Local\Temp\ipykernel_4864\60782308.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Attrition"].replace({"yes":1,"no":0}, inplace = True)
C:\Users\Anaam Ullah\AppData\Local\Temp\ipykernel_4864\60782308.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Attrition"].replace({"Yes":1,"No":0}, inplace = True)
C:\Users\Anaam Ullah\AppData\Local\Temp\ipykernel_4864\60782308.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Attrition"].replace({"Yes":1,"No":0}, inplace = True)

In [29]:
df

   Age  Department JobSatisfaction  YearsAtCompany  OverTime  Attrition
1   36     Finance               2              11         0          1
2   29     Finance               3               7         1          1
3   42  Operations               4               5         1          0
4   40          HR               1              10         0          0
5   44     Finance               2               2         0          0
7   32         R&D               1               2         1          0
8   45     Finance               4               4         1          1
9   57  Operations               1              14         1          0
10  45  Operations               2              13         0          1
11  24     Finance               3               2         1          0
13  23  Operations               4               4         1          0
14  45  Operations               2               9         1          0
16  59         R&D               4              14         1          1
17  23          HR               4              13         1          1
18  42         R&D               4               6         1          0
19  54         R&D               1              10         0          0
20  33     Finance               1               8         1          0
21  43          HR               1              14         1          1
22  46       Sales               3              14         0          1
23  48  Operations               1               9         0          0
24  49         R&D               1               9         1          1
25  37          HR               1              11         0          1
26  36     Finance               3              12         1          0
27  24  Operations               1               2         1          1
28  58       Sales               4              14         1          1
29  28       Sales               1               6         0          1
30  42       Sales               4               0         0          0
31  30       Sales               4               3         1          0
32  39         R&D               4              12         1          0
34  46         R&D               3              13         0          1
35  35     Finance               3               4         0          1
36  30     Finance               1               6         1          0
37  47          HR               5               6         1          0
38  23         R&D               3              12         1          1
39  41       Sales               2              14         0          1
40  49         R&D               1              10         0          0
41  28         R&D               3              12         1          0
42  29       Sales               1               3         1          1
43  56     Finance               2              12         0          0
44  35  Operations               3               6         1          1
45  38  Operations               2              10         0          0
46  57  Operations               1               2         0          0
47  25          HR               4               5         1          1
48  23         R&D               3              11         1          1
49  27  Operations               1               1         0          1
50  25       Sales               4               9         1          1
51  50         R&D               4              12         0          0
52  39       Sales               2              13         0          1
53  47       Sales               1               8         1          0
54  55     Finance               4               4         0          0
55  31         R&D               3               5         1          1
56  57  Operations               3              11         1          0
57  35         R&D               2              11         0          0
58   0         R&D               4              11         1          1
59  36       Sales               1              11         1          1

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 55 entries, 1 to 59
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              55 non-null     object
 1   Department       55 non-null     object
 2   JobSatisfaction  55 non-null     object
 3   YearsAtCompany   55 non-null     int64
 4   OverTime         55 non-null     int64
 5   Attrition        55 non-null     int64
dtypes: int64(3), object(3)
memory usage: 3.0+ KB

In [32]:
df['JobSatisfaction'] = df['JobSatisfaction'].str.replace(",","").astype(int)

C:\Users\Anaam Ullah\AppData\Local\Temp\ipykernel_4864\2423056866.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['JobSatisfaction'] = df['JobSatisfaction'].str.replace(",","").astype(int)

In [35]:
df['Age'] = df['Age'].str.replace(",","").astype(int)

C:\Users\Anaam Ullah\AppData\Local\Temp\ipykernel_4864\3783121354.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'] = df['Age'].str.replace(",","").astype(int)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 55 entries, 1 to 59
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              55 non-null     int64
 1   Department       55 non-null     object
 2   JobSatisfaction  55 non-null     int64
 3   YearsAtCompany   55 non-null     int64
 4   OverTime         55 non-null     int64
 5   Attrition        55 non-null     int64
dtypes: int64(5), object(1)
memory usage: 3.0+ KB

In [68]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer

ohe = OneHotEncoder()
ohe.fit(df[["Department"]])


ct = make_column_transformer((OneHotEncoder(categories=ohe.categories_),["Department"]), remainder = "passthrough")
#x = ct.fit_transform(df.drop("Attrition", axis = 1))
x = df.drop("Attrition", axis = 1)

y = df["Attrition"]

In [69]:
from sklearn.linear_model import LogisticRegression
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [70]:
lr = LogisticRegression()
pipe = make_pipeline(ct,lr)
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 42)
pipe.fit(x_train, y_train) 
y_pred = pipe.predict(x_test)

In [54]:
y_pred

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1])

In [57]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7272727272727273

In [58]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.75      0.80         8
           1       0.50      0.67      0.57         3

    accuracy                           0.73        11
   macro avg       0.68      0.71      0.69        11
weighted avg       0.76      0.73      0.74        11

In [71]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Finance', 'HR', 'Operations', 'R&D', 'Sales'], dtype=object)]),
                                                  ['Department'])])),
                ('logisticregression', LogisticRegression())])

In [72]:
import joblib
joblib.dump(pipe, 'logistic_regression_model.pkl')

['logistic_regression_model.pkl']

In [73]:
import streamlit as st